# Generated by Django 4.2.16 on 2024-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=255),
        ),
    ]
