# Generated by Django 4.2.16 on 2024-12-01 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_rename_updated_at_document_last_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
