# Generated by Django 4.2.16 on 2024-12-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_rename_last_modified_document_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=255),
        ),
    ]
